# Generated by Django 3.2.8 on 2021-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('numpy', 'Numpy'), ('java', 'Core Java')], max_length=20),
        ),
    ]
